language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t jeffox22/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run jeffox22/react-test npm test -- --coverage

after_success:
  - docker build -t jeffox22/multi-client ./client
  - docker build -t jeffox22/multi-nginx ./nginx
  - dockker build -t jeffox22/multi-server ./server
  - docker build -t jeffox22/multi-worker ./worker
  # login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # push images to docker hub
  - docker push jeffox22/multi-client
  - docker push jeffox22/multi-nginx
  - docker push jeffox22/multi-server
  - docker push jeffox22/multi-worker
